import {
  ADD_POINT,
  addPoint,
  DELETE_TIME_ACTION,
  deleteTimeAction,
  EDIT_TIME_ACTION,
  editTimeAction,
  FETCHED,
  fetched,
  FETCHED_HAS_ERROR,
  fetchedHasError,
  IS_FETCHING,
  fetching,
  FIND_RESTAURANTS,
  findRestaurants,
  REPORT_TIME_ACTION,
  reportTimeAction,
  GET_USERS,
  getUsers,
  GET_USER_REPORTS,
  getUserReports,
  LOGIN_ACTION,
  loginAction,
  SIGN_UP_ACTION,
  signupAction,
  CLEAR_ERROR,
  clearError
} from "./index";

import { wait2plateReducer } from "./index";
